# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 23:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_title', models.CharField(max_length=100)),
                ('album_description', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('album_date', models.DateTimeField(verbose_name='event date')),
                ('album_location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_id', models.IntegerField()),
                ('picture_dir', models.CharField(max_length=100)),
                ('picture_file', models.CharField(max_length=100)),
                ('picture_date', models.DateTimeField(verbose_name='picture date')),
                ('picture_description', models.CharField(max_length=255)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Album')),
            ],
        ),
    ]
