# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='event date'),
        ),
        migrations.AlterField(
            model_name='album',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='picture_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='picture date'),
        ),
    ]
