# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_picture_picture_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='picture_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
