# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20171128_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='picture',
            name='picture_description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='picture',
            name='picture_dir',
            field=models.CharField(default='dir', max_length=100),
        ),
        migrations.AlterField(
            model_name='picture',
            name='picture_file',
            field=models.CharField(default='file', max_length=100),
        ),
    ]
